### ISSUE TITLE
GKE should allow 100 GiB Basic_HDD but doesn't seem to

### ISSUE THREAD

**Issue by ggprod** [kubernetes-sigs/gcp-filestore-csi-driver#1119]
According to the docs for GKE 1.32 and above it should be possible to provision BASIC_HDD sizes of 100 GiB, but when I try to do that I get 1 TiB instances intstead
https://cloud.google.com/filestore/docs/csi-driver#requirements

I have a GKE cluster using the current stable (which is above 1.32), installed the latest Filestore CSI driver per the instructions and created a storage class like this (to use a non-default network):
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-data-vpc
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: BASIC_HDD
  network: data-vpc
```

and a PVC like this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: airflow
    release: openmetadata-dependencies
  name: openmetadata-dependencies-dags
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: filestore-data-vpc
```

But I end up with a Filestore instance with capacity 1 TiB

<img width="1328" alt="Image" src="https://github.com/user-attachments/assets/29810097-642f-4e06-a9c8-bb1d02691f59" />
<img width="1637" alt="Image" src="https://github.com/user-attachments/assets/e2c6d758-0ec5-4f11-a340-f893a15d2761" />
<img width="499" alt="Image" src="https://github.com/user-attachments/assets/dd15da96-ff44-4723-b526-8996e8dd1eed" />

How do I get the 100 GiB instance created?
