### ISSUE TITLE
Filestore driver sends error while creating snapshot

### ISSUE THREAD

**Issue by chaitanya-baraskar** [kubernetes-sigs/gcp-filestore-csi-driver#221]
Filestore driver sends error while creating snapshot. Now, I am not sure whether this is expected behaviour or not. While polling for `volumesnapshot` status using Dynamic Kube cli it gets confusing as to consider error or not. Volumesnapshot eventually sets `ReadyToUse` flag to `true`. If VolumeSnapshot is getting created is it necessary to send error stating that `current State Created`. I have shared sample logs and yaml files I have used.

Deployment with Filestore CSI PVC.
``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web-server
          image: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: pvc-1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-rwx
  resources:
    requests:
      storage: 1Ti
```

Sample VolumeSnapshot yaml - 
```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot
spec:
  volumeSnapshotClassName: csi-gcp-filestore-backup-snap-class
  source:
    persistentVolumeClaimName: pvc-1
```

VolumeSnapshotClass yaml -
```
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: filestore.csi.storage.gke.io
kind: VolumeSnapshotClass
metadata:
  annotations:
  creationTimestamp: "2022-02-10T09:57:33Z"
  generation: 1
  name: csi-gcp-filestore-backup-snap-class
  resourceVersion: "104941"
  uid: b50cb0b0-c2ea-4c48-bb50-b8167b4fba4a
parameters:
  type: backup
```

Error I found in controller pod - 

```
E0221 13:46:40.708660       1 snapshot_controller.go:122] checkandUpdateContentStatus [snapcontent-a0e5a9d7-dbaa-48cb-b560-9939e360e6b9]: error occurred failed to take snapshot of the volume modeInstance/us-west1-c/pvc-a99c1776-34dd-4691-a415-18c7c3b1bea4/vol1: "rpc error: code = DeadlineExceeded desc = Backup <redacted> not yet ready, current state CREATING"


E0221 13:46:56.127621       1 snapshot_controller.go:122] checkandUpdateContentStatus [snapcontent-a0e5a9d7-dbaa-48cb-b560-9939e360e6b9]: error occurred failed to take snapshot of the volume modeInstance/us-west1-c/pvc-a99c1776-34dd-4691-a415-18c7c3b1bea4/vol1: "rpc error: code = DeadlineExceeded desc = Backup <redacted> not yet ready, current state FINALIZING"
```

I haven't shared all logs. Just took few for sample.

Please let me know if more information is needed.
