### ISSUE TITLE
Support FQDN ( DNS Name ) in addition to IP for filestore.csi.storage.gke.io driver

### ISSUE THREAD

**Issue by ronak-dhiravani** [kubernetes-sigs/gcp-filestore-csi-driver#584]
Below is snippet of Persistent Volume manifest file I am using for GCP Filestore. I want to use DNS name we have created in Cloud DNS for that filestore instead of IP, which is I think no supported for now.
```
csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: my-pv-volume-handle
    volumeAttributes:
      ip: 1.2.3.4
      volume: /data
```
